name: SongTypes
form: $/csatar/knowledgerepository/models/songtype/fields.yaml
modelClass: Csatar\KnowledgeRepository\Models\SongType
defaultRedirect: csatar/knowledgerepository/songtypes
create:
    redirect: 'csatar/knowledgerepository/songtypes/update/:id'
    redirectClose: csatar/knowledgerepository/songtypes
update:
    redirect: csatar/knowledgerepository/songtypes
    redirectClose: csatar/knowledgerepository/songtypes
